ENVIRONMENT:
  MAX_EPISODE_STEPS: 2000
SIMULATOR:
  AGENT_0:
    SENSORS: ['DEPTH_SENSOR']
  HABITAT_SIM_V0:
    GPU_DEVICE_ID: 0
  RGB_SENSOR:
    WIDTH: 256
    HEIGHT: 256
  DEPTH_SENSOR:
    WIDTH: 256
    HEIGHT: 256
TASK:
  TYPE: Nav-v0
  SENSORS: ['POINTGOAL_SENSOR','EPO_GPS_AND_COMPASS']
  POINTGOAL_SENSOR:
    TYPE: PointGoalSensor
    GOAL_FORMAT: POLAR
  MEASUREMENTS: ['ROOMNAVMETRIC']
  ROOMNAVMETRIC:
    TYPE: RoomNavMetric
  SPL:
    TYPE: SPL
    SUCCESS_DISTANCE: 0.2
  
DATASET:
  TYPE: RoomNav-v1
  SPLIT: train
  DATA_PATH: data/datasets/roomnav/mp3d/v1/{split}/{split}.json.gz
    